GRANT CONNECT ON DATABASE live_watt_db TO live_watt_user;

GRANT USAGE ON SCHEMA public TO live_watt_user;
GRANT CREATE ON SCHEMA public TO live_watt_user;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO live_watt_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO live_watt_user;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO live_watt_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT USAGE, SELECT ON SEQUENCES TO live_watt_user;